### ISSUE TITLE
The deleted campaign appears in the interface data

### ISSUE THREAD

**Issue by z574438205** [yahoojp-marketing/sponsored-search-api-java-samples#11]
Hello, 

I successfully through the interface request to the Campaign data, but in the return data to see the deleted Campaign is also in the data, how to allow the interface does not return to the deleted Campaign?

![image](https://cloud.githubusercontent.com/assets/20828160/21217781/eb5e7d0e-c2e8-11e6-944f-06b27af7e9cf.png)

![image](https://cloud.githubusercontent.com/assets/20828160/21217788/f8353054-c2e8-11e6-9439-13ed857a966f.png)

Looking forward to your reply

Thank you!

**Comment by yahoojp-marketingsolutions** [comment]
Thank you for your feedback!
The issue has been resolved and the system now works properly.

Regards:)
Yahoo! JAPAN Marketing Solutions
